### ISSUE TITLE
Calculate hexagons for map extent not working in ArcGIS Pro

### ISSUE THREAD

**Issue by dtiede** [ZGIS/ZonalMetrics-Toolbox_ArcGIS_Pro#1]
in ArcGIS Pro the mapping module changed - therefore the map extent cannot be retrieved on the fly (only if a project is saved, which makes no sense in the current workflow).

Workaround: 
Disable the calculation for the display extent (not preferred)
Enable additional user input for the extent?

**Comment by LAGIS-BR** [comment]
same problem...
what is meant with if a prject is saved?

**Comment by dtiede** [comment]
that issue is solved. Did you try it with the newest version?

**Comment by LAGIS-BR** [comment]
Sorry, but there is still a problem....
The newest version is the one you updated 14 days ago?

Running script CreateHexagons...
ZonalMetricsTool version: 2020324_11
Debug mode disabled
create hexagon layer....
height: 50.0
width: 86.60254037844386
 Traceback (most recent call last):
  File "<string>", line 1651, in execute
  File "<string>", line 1778, in updateOrigin
ValueError: could not convert string to float: '5689478,1331'
 Failed to execute (CreateHexagons).
